name: Change and Commit Yaml
author: SumUp
description: This Action clones a repository, then changes a Yaml file inside it and pushes the changes
branding:
  icon: git-commit
  color: gray-dark
inputs:
  repository:
    description: The repository to clone and then push
    required: true
  ref:
    description: The branch, tag or SHA to checkout
    required: false
    default: ''
  filepath:
    description: Path to the file to be changed
    required: true
  yamlpath:
    description: Path to the yaml file to be changed
    required: true
  newvalue:
    description: New value to be inserted in the yaml file
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: 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
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: ccy-repo
    - name: Change Yaml
      shell: bash
      env:
        FILEPATH: ${{ inputs.filepath }}
        YAMLPATH: ${{ inputs.yamlpath }}
        NEWVALUE: ${{ inputs.newvalue }}
        VERSION: v4.25.2
        BINARY: yq_linux_amd64
      run: |
        wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
        tar xz && mv ${BINARY} /usr/local/bin/yq
        yq -i "${YAMLPATH} = \"${NEWVALUE}\"" ${FILEPATH}
    - name: Commit and Push Changes
      uses: EndBug/add-and-commit@v9.0.0
      with:
        cwd: ccy-repo
        add: ${{ inputs.filepath }}
        author_name: GHActions
        author_email: sumup@sumup.com
        message: "Automated changes: ${{ inputs.filepath }}"
        pull: --rebase --autostash
        push: true
    - run: rm -rf ccy-repo
      shell: bash
