name: Change and Commit Yaml
author: SumUp
description: This Action clones a repository, then changes a Yaml file inside it and pushes the changes
branding:
  icon: git-commit
  color: gray-dark
inputs:
  filepath:
    description: Path to the file to be changed
    required: true
  newvalue:
    description: New value to be inserted in the yaml file
    required: true
  ref:
    description: The branch, tag or SHA to checkout
    required: true
  repository:
    description: The repository to clone and then push
    required: true
  yamlpath:
    description: Path to the yaml file to be changed
    required: true
  commitprefix:
    description: Prefix to be added to the commit message
    required: false
    default: '[CCY]'
  token:
    description: The token used to authenticate with GitHub
    default: ${{ github.token }}
    required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: ccy-repo
        token: ${{ inputs.token }}
    - name: Change Yaml
      shell: bash
      env:
        FILEPATH: ${{ inputs.filepath }}
        YAMLPATH: ${{ inputs.yamlpath }}
        NEWVALUE: ${{ inputs.newvalue }}
        VERSION: v4.25.2
        BINARY: yq_linux_amd64
      run: |
        wget -q https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz -O - |\
        tar xz && mv ${BINARY} /usr/local/bin/yq
        yq -i "${YAMLPATH} = \"${NEWVALUE}\"" ccy-repo/${FILEPATH}
    - name: Commit and Push Changes
      working-directory: ccy-repo
      shell: bash
      env:
        COMMITPREFIX: ${{ inputs.commitprefix }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ${{ inputs.filepath }} || {
          echo "No files were changed, so we did not commit anything"
          exit 1
        } && \
        git commit -m "$COMMITPREFIX Automated changes to ${{ inputs.filepath }}" && \
        git push origin ${{ inputs.ref }}
    - run: rm -rf ccy-repo
      shell: bash
