name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Action
        uses: sumup-bank/change-commit-yaml@main
        with:
          repository: sumup-bank/change-commit-yaml
          filepath: tests/tests.yaml
          yamlpath: .commit.hash
          newvalue: ${{ env.GITHUB_SHA }}
